### ISSUE TITLE
Rush Point - Slient Aim

### ISSUE THREAD

**Issue by PhongRobloxVN** [Stefanuk12/ROBLOX#15] opened 2022-01-16 08:07 UTC
Every time i execute the script, it just straight out freeze the game 

Executor: Synapse X
OS: Windows 11

**Comment by Stefanuk12** [comment] 2022-01-16 08:24
> Every time i execute the script, it just straight out freeze the game 
> 
> 
> 
> Executor: Synapse X
> 
> OS: Windows 11
> 
> 

alright, will look into it soon. likely patched

**Comment by Stefanuk12** [comment] 2022-01-16 18:10
Duplicate of #14

**Closed as completed by Stefanuk12** 2022-01-16 18:10 UTC
Labels: bug
